use crate::syscall::consts::*;
use crate::syscall::{ffi, frame::SyscallFrame, kdbg, stats};

use super::{console, fd_driver_dl, fs, net, process, storage, ui, user};

fn time_ms() -> u64 {
    let hz = unsafe { ffi::clks_interrupts_timer_hz() as u64 };
    if hz == 0 {
        return 0;
    }
    unsafe { ffi::clks_interrupts_timer_ticks().saturating_mul(1000) / hz }
}


pub fn dispatch(frame: &mut SyscallFrame) -> u64 {
    match frame.rax {
        LOG_WRITE => console::log_write(frame.rbx, frame.rcx),
        TIMER_TICKS => unsafe { ffi::clks_interrupts_timer_ticks() },
        TIMER_HZ => unsafe { ffi::clks_interrupts_timer_hz() as u64 },
        TIME_MS => time_ms(),
        TASK_COUNT => unsafe { ffi::clks_scheduler_get_stats().task_count as u64 },
        CURRENT_TASK_ID => unsafe { ffi::clks_scheduler_get_stats().current_task_id as u64 },
        SERVICE_COUNT => unsafe { ffi::clks_service_count() },
        SERVICE_READY_COUNT => unsafe { ffi::clks_service_ready_count() },
        CONTEXT_SWITCHES => unsafe { ffi::clks_scheduler_get_stats().context_switch_count },
        RESERVED_7 | RESERVED_8 => U64_MAX,
        FS_NODE_COUNT => unsafe { ffi::clks_fs_node_count() },
        FS_CHILD_COUNT => fs::child_count(frame.rbx),
        FS_GET_CHILD_NAME => fs::get_child_name(frame.rbx, frame.rcx, frame.rdx),
        FS_READ => fs::read(frame.rbx, frame.rcx, frame.rdx),
        EXEC_PATH => process::exec_path(frame.rbx),
        EXEC_PATHV => process::exec_pathv(frame.rbx, frame.rcx, frame.rdx),
        EXEC_PATHV_IO => process::exec_pathv_io(frame.rbx, frame.rcx, frame.rdx),
        EXEC_REQUESTS => unsafe { ffi::clks_exec_request_count() },
        EXEC_SUCCESS => unsafe { ffi::clks_exec_success_count() },
        USER_SHELL_READY => if unsafe { ffi::clks_userland_shell_ready() } != 0 { 1 } else { 0 },
        USER_EXEC_REQUESTED => if unsafe { ffi::clks_userland_shell_exec_requested() } != 0 { 1 } else { 0 },
        USER_LAUNCH_TRIES => unsafe { ffi::clks_userland_launch_attempts() },
        USER_LAUNCH_OK => unsafe { ffi::clks_userland_launch_success() },
        USER_LAUNCH_FAIL => unsafe { ffi::clks_userland_launch_failures() },
        TTY_COUNT => unsafe { ffi::clks_tty_count() as u64 },
        TTY_ACTIVE => unsafe { ffi::clks_tty_active() as u64 },
        TTY_SWITCH => {
            unsafe { ffi::clks_tty_switch(frame.rbx as u32) };
            unsafe { ffi::clks_tty_active() as u64 }
        }
        TTY_WRITE => console::tty_write(frame.rbx, frame.rcx),
        TTY_WRITE_CHAR => console::tty_write_char(frame.rbx),
        KBD_GET_CHAR => console::kbd_get_char(),
        FS_STAT_TYPE => fs::stat_type(frame.rbx),
        FS_STAT_SIZE => fs::stat_size(frame.rbx),
        FS_MKDIR => fs::mkdir(frame.rbx),
        FS_WRITE => fs::write(frame.rbx, frame.rcx, frame.rdx),
        FS_APPEND => fs::append(frame.rbx, frame.rcx, frame.rdx),
        FS_REMOVE => fs::remove(frame.rbx),
        LOG_JOURNAL_COUNT => console::log_journal_count(),
        LOG_JOURNAL_READ => console::log_journal_read(frame.rbx, frame.rcx, frame.rdx),
        KBD_BUFFERED => unsafe { ffi::clks_keyboard_buffered_count() },
        KBD_PUSHED => unsafe { ffi::clks_keyboard_push_count() },
        KBD_POPPED => unsafe { ffi::clks_keyboard_pop_count() },
        KBD_DROPPED => unsafe { ffi::clks_keyboard_drop_count() },
        KBD_HOTKEY_SWITCHES => unsafe { ffi::clks_keyboard_hotkey_switch_count() },
        GETPID => process::getpid(),
        SPAWN_PATH => process::spawn_path(frame.rbx),
        SPAWN_PATHV => process::spawn_pathv(frame.rbx, frame.rcx, frame.rdx),
        WAITPID => process::waitpid(frame.rbx, frame.rcx),
        PROC_ARGC => process::proc_argc(),
        PROC_ARGV => process::proc_argv(frame.rbx, frame.rcx, frame.rdx),
        PROC_ENVC => process::proc_envc(),
        PROC_ENV => process::proc_env(frame.rbx, frame.rcx, frame.rdx),
        PROC_LAST_SIGNAL => process::proc_last_signal(),
        PROC_FAULT_VECTOR => process::proc_fault_vector(),
        PROC_FAULT_ERROR => process::proc_fault_error(),
        PROC_FAULT_RIP => process::proc_fault_rip(),
        PROC_COUNT => process::proc_count(),
        PROC_PID_AT => process::proc_pid_at(frame.rbx, frame.rcx),
        PROC_SNAPSHOT => process::proc_snapshot(frame.rbx, frame.rcx, frame.rdx),
        PROC_KILL => process::proc_kill(frame.rbx, frame.rcx),
        EXIT => process::exit(frame.rbx),
        SLEEP_TICKS => process::sleep_ticks(frame as *mut SyscallFrame, frame.rbx),
        SLEEP_MS => process::sleep_ms(frame as *mut SyscallFrame, frame.rbx),
        YIELD => process::yield_now(frame as *mut SyscallFrame),
        SHUTDOWN => process::shutdown(),
        RESTART => process::restart(),
        AUDIO_AVAILABLE => console::audio_available(),
        AUDIO_PLAY_TONE => console::audio_play_tone(frame.rbx, frame.rcx),
        AUDIO_STOP => console::audio_stop(),
        KDBG_SYM => kdbg::sym(frame.rbx, frame.rcx, frame.rdx),
        KDBG_BT => kdbg::bt(frame.rbx),
        KDBG_REGS => kdbg::regs(frame.rbx, frame.rcx),
        STATS_TOTAL => stats::total_count(),
        STATS_ID_COUNT => stats::id_count(frame.rbx),
        STATS_RECENT_WINDOW => stats::recent_window(),
        STATS_RECENT_ID => stats::recent_id(frame.rbx),
        FD_OPEN => fd_driver_dl::fd_open(frame.rbx, frame.rcx, frame.rdx),
        FD_READ => fd_driver_dl::fd_read(frame.rbx, frame.rcx, frame.rdx),
        FD_WRITE => fd_driver_dl::fd_write(frame.rbx, frame.rcx, frame.rdx),
        FD_CLOSE => fd_driver_dl::fd_close(frame.rbx),
        FD_DUP => fd_driver_dl::fd_dup(frame.rbx),
        DL_OPEN => fd_driver_dl::dl_open(frame.rbx),
        DL_CLOSE => fd_driver_dl::dl_close(frame.rbx),
        DL_SYM => fd_driver_dl::dl_sym(frame.rbx, frame.rcx),
        FB_INFO => console::fb_info(frame.rbx),
        FB_BLIT => console::fb_blit(frame.rbx),
        FB_CLEAR => console::fb_clear(frame.rbx),
        DISPLAY_INFO => console::display_info(frame.rbx, frame.rcx),
        DISPLAY_SET_MODE => console::display_set_mode(frame.rbx),
        TTY_GRID_INFO => console::tty_grid_info(frame.rbx),
        INPUTM_COUNT => ui::inputm_count(),
        INPUTM_INFO => ui::inputm_info(frame.rbx, frame.rcx, frame.rdx),
        INPUTM_CURRENT => ui::inputm_current(),
        INPUTM_SELECT => ui::inputm_select(frame.rbx),
        INPUTM_REGISTER => ui::inputm_register(frame.rbx),
        INPUTM_REGISTER_RULE => ui::inputm_register_rule(frame.rbx),
        TTY_STATUS_SET => ui::tty_status_set(frame.rbx),
        KERNEL_VERSION => storage::kernel_version(frame.rbx, frame.rcx),
        DISK_PRESENT => storage::disk_present(),
        DISK_SIZE_BYTES => storage::disk_size_bytes(),
        DISK_SECTOR_COUNT => storage::disk_sector_count(),
        DISK_FORMATTED => storage::disk_formatted(),
        DISK_FORMAT_FAT32 => storage::disk_format_fat32(frame.rbx),
        DISK_MOUNT => storage::disk_mount(frame.rbx),
        DISK_MOUNTED => storage::disk_mounted(),
        DISK_MOUNT_PATH => storage::disk_mount_path(frame.rbx, frame.rcx),
        DISK_READ_SECTOR => storage::disk_read_sector(frame.rbx, frame.rcx),
        DISK_WRITE_SECTOR => storage::disk_write_sector(frame.rbx, frame.rcx),
        NET_AVAILABLE => net::available(),
        NET_IPV4_ADDR => net::ipv4_addr(),
        NET_PING => net::ping(frame.rbx, frame.rcx),
        NET_UDP_SEND => net::udp_send(frame.rbx),
        NET_UDP_RECV => net::udp_recv(frame.rbx),
        NET_NETMASK => net::netmask(),
        NET_GATEWAY => net::gateway(),
        NET_DNS_SERVER => net::dns_server(),
        NET_TCP_CONNECT => net::tcp_connect(frame.rbx),
        NET_TCP_LISTEN => net::tcp_listen(frame.rbx),
        NET_TCP_ACCEPT => net::tcp_accept(frame.rbx),
        NET_TCP_SEND => net::tcp_send(frame.rbx),
        NET_TCP_RECV => net::tcp_recv(frame.rbx),
        NET_TCP_CLOSE => net::tcp_close(frame.rbx),
        NET_TCP_LAST_ERROR => net::tcp_last_error(),
        VM_ALLOC => unsafe { ffi::clks_exec_vm_alloc(frame.rbx, frame.rcx) },
        VM_FREE => unsafe { ffi::clks_exec_vm_free(frame.rbx, frame.rcx) },
        USER_CURRENT => user::current(frame.rbx),
        USER_LOGIN => user::login(frame.rbx),
        USER_LOGOUT => user::logout(),
        USER_COUNT => user::count(),
        USER_AT => user::at(frame.rbx, frame.rcx),
        USER_ADD => user::add(frame.rbx),
        USER_PASSWD => user::passwd(frame.rbx),
        USER_SET_ROLE => user::set_role(frame.rbx, frame.rcx),
        USER_REMOVE => user::remove(frame.rbx),
        USER_IS_ADMIN => user::is_admin(),
        DISK_FSCK_FAT32 => storage::disk_fsck_fat32(frame.rbx, frame.rcx),
        SYSINFO => storage::sysinfo(frame.rbx, frame.rcx),
        LOCALE_GET => storage::locale_get(frame.rbx, frame.rcx),
        LOCALE_SET => storage::locale_set(frame.rbx),
        BOOT_CMDLINE => storage::boot_cmdline(frame.rbx, frame.rcx),
        MMAP => process::mmap(frame.rbx),
        MOUSE_STATE => ui::mouse_state(frame.rbx),
        WM_CREATE => ui::wm_create(frame.rbx),
        WM_DESTROY => ui::wm_destroy(frame.rbx),
        WM_PRESENT => ui::wm_present(frame.rbx),
        WM_POLL_EVENT => ui::wm_poll_event(frame.rbx, frame.rcx),
        WM_MOVE => ui::wm_move(frame.rbx),
        WM_SET_FOCUS => ui::wm_set_focus(frame.rbx),
        WM_SET_FLAGS => ui::wm_set_flags(frame.rbx, frame.rcx),
        WM_RESIZE => ui::wm_resize(frame.rbx),
        PTY_OPEN => fd_driver_dl::pty_open(),
        WM_COUNT => ui::wm_count(),
        WM_ID_AT => ui::wm_id_at(frame.rbx, frame.rcx),
        WM_SNAPSHOT => ui::wm_snapshot(frame.rbx, frame.rcx, frame.rdx),
        USER_HEAP_ALLOC => unsafe { ffi::clks_exec_user_heap_alloc(frame.rbx) },
        DRIVER_COUNT => fd_driver_dl::driver_count(),
        DRIVER_INFO => fd_driver_dl::driver_info(frame.rbx, frame.rcx, frame.rdx),
        DRIVER_LOAD => fd_driver_dl::driver_load(frame.rbx),
        DRIVER_UNLOAD => fd_driver_dl::driver_unload(frame.rbx),
        DRIVER_RELOAD => fd_driver_dl::driver_reload(),
        _ => U64_MAX,
    }
}
