/* Exec runtime is split into include modules but kept as one translation unit. */
#include "exec/common.inc"
#include "exec/log.inc"
#include "exec/path_util.inc"
#include "exec/vm.inc"
#include "exec/dynlib.inc"
#include "exec/argv_env.inc"
#include "exec/signal.inc"
#include "exec/process.inc"
#include "exec/fd.inc"
#include "exec/runtime.inc"
#include "exec/fd_api.inc"
#include "exec/dynlib_api.inc"
#include "exec/vm_api.inc"
#include "exec/current.inc"
#include "exec/proc_api.inc"
#include "exec/signal_api.inc"
#include "exec/tick.inc"
